#=========================================#
# Plugin Custom NPC Made By HighestDreams #
#=========================================#
# Cool-down message will send to player when click too fast on NPC
cooldown-message: "§l§cYou are hitting too fast!"
# NPC rotation distance (Per block!)
rotation-distance: 5
# Select your language, the form's language will change to what ever you select HERE!
# Available languages:
# en (English)
# ru (Russian)
# ge (Germany)
# ch (Chinese)
# je (Japanese)
# ko (Korean)
# fr (French)
language: "en"